### ISSUE TITLE
URLError: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#187]
View details in Rollbar: [https://rollbar.com/vlabs/Venue/items/34/](https://rollbar.com/vlabs/Venue/items/34/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "./venue/views.py", line 544, in check_profile
    info = get_user_position(forum.id, data.get('forum_user_id'), user.id)
  File "/usr/local/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "./venue/tasks.py", line 191, in get_user_position
    status_code, position, username = scraper.get_user_position(forum_user_id)
  File "./venue/scrapers/bitcointalk.py", line 276, in get_user_position
    scraper.get_profile(forum_user_id)
  File "./venue/scrapers/bitcointalk.py", line 64, in get_profile
    DesiredCapabilities.CHROME
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by shawnlauzon** [comment]
I believe this can be reproduced by hitting this url: `https://venue-dev.volentix.io/api/check/profile/?forum_id=1&forum_user_id=1216831`; it returns an HTTP 500

**Comment by shawnlauzon** [comment]
@realrhys This is the call that the API makes, and has been making for awhile, so it's not a problem with the API call itself

**Comment by shawnlauzon** [comment]
So just to summarize: 

- Bitcointalk now seems to be blocking us.
- The selenium server's purpose is to query the server using a web browser instead of hubless
- We actually don't know if using selenium will solve the problem, because they might have blocked our IP.

So my question is how simple is it to test and see if selenium solves the problem. If so, then perhaps we can just go with that. If it is either difficult, or the same complexity as some IP rotation solution, perhaps that would be better.

Thoughts @alexdashkov @realrhys?

**Comment by alexdashkov** [comment]
So I can't reproduce this error. I suppose that it was some temporary block like @joemarct had written in the #140. Please let me know what to do with it(set up selenium, set up a proxy, something else)?

**Comment by shawnlauzon** [comment]
Yes, setup the IP scraping rotation system we discussed earlier.

**Comment by alexdashkov** [comment]
Ok, in this case, I have to get an API key to make the tests. Please PM me.

**Comment by shawnlauzon** [comment]
PM'd on Riot
