### ISSUE TITLE
ScraperError: Cannot get username

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#206]
View details in Rollbar: [https://rollbar.com/vlabs/Venue/items/14/](https://rollbar.com/vlabs/Venue/items/14/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/venue/tasks.py", line 81, in scrape_forum_profile
    test_signature=forum_profile.signature.test_signature)
  File "/code/venue/scrapers/bitcointalk.py", line 264, in verify_and_scrape
    username = scraper.get_username()
  File "/code/venue/scrapers/bitcointalk.py", line 108, in get_username
    raise ScraperError('Cannot get username')
ScraperError: Cannot get username
```

**Comment by alexdashkov** [comment]
The same thing as before, I can do nothing without extra info, so I'm waiting for the https://github.com/Volentix/venue-server/pull/209 to add logDNA

**Comment by shawnlauzon** [comment]
Just sent LogDNA access to @alexdashkov
