### ISSUE TITLE
MaxRetriesExceededError: Can't retry venue.tasks.compute_points[baf2fc22-99b9-4588-9883-3926dff61beb] args:(['57eaef9e-80da-4663-9df8-7b58449b4452', '4457431e-ddc1-4bac-b144-da4a94c1b912', '37e3287f-39a6-4558-82d2-79959bdb4b1a', 'cf426054-a2a4-4889-ad17-b

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#208]
View details in Rollbar: [https://rollbar.com/vlabs/Venue/items/24/](https://rollbar.com/vlabs/Venue/items/24/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/venue/tasks.py", line 310, in compute_points
    self.retry(countdown=5)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 672, in retry
    self.name, request.id, S.args, S.kwargs))
MaxRetriesExceededError: Can't retry venue.tasks.compute_points[52e7d9d4-d4ef-4dc0-bea2-7f1e487b295c] args:(['c51bb3a7-911a-4188-a00a-d70b2ed45e7a', '6da93560-ae44-466c-abe9-d60e5ccd2358', '0b99850c-9f89-4d3b-b520-d658382c1d18', 'a8a2e022-5a11-4700-b47a-f0c32e0d6f43', '5658fb3d-4216-4d86-8089-45abdc799470', 'a2fea05d-c2b5-4a04-a135-a1e6409a51fe', 'e59cc917-fdb0-4e9d-8590-b4d8891194cd', 'a3f3a56e-cb16-466e-b218-56cb24e6a2ed', 'cbc1296b-1719-4ddf-8b02-b5a05df50b7a', '6964e351-0e34-4547-aa8c-595f14fe1229', '5da81df6-484f-4e33-8a8e-452b81b97dbd', '2d347532-a0c7-4e85-a827-9d79dceed06f'],) kwargs:{}
```

**Comment by joemarct** [comment]
Looks like the scraper experiences occasional blockage

It fails because it couldn't find the username on the page. And the computation of points does not proceed until the scraping works but only up to 600 retries.

So it tried 600 times to scrape (with a pause of 5 seconds per retry) then it gave with MaxRetriesExceeded error.
