### ISSUE TITLE
DoesNotExist: ForumProfile matching query does not exist.

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#218]
View details in Rollbar: [https://rollbar.com/vlabs/Venue/items/39/](https://rollbar.com/vlabs/Venue/items/39/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/venue/tasks.py", line 78, in scrape_forum_profile
    forum_profile = ForumProfile.objects.get(id=forum_profile_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: ForumProfile matching query does not exist.
```

**Comment by shawnlauzon** [comment]
Duplicate of #144
