### ISSUE TITLE
ScraperError: ('Error in scraping forum user ID 689228', {'fallback': 'crawlera', 'status_code': 200, 'response_text': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns=

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#230]
View details in Rollbar: [https://rollbar.com/vlabs/Venue/items/42/](https://rollbar.com/vlabs/Venue/items/42/)

```
Traceback (most recent call last):
  File "/code/venue/tasks.py", line 289, in get_user_position
    fallback=fallback
  File "/code/venue/scrapers/bitcointalk.py", line 323, in get_user_position
    raise ScraperError(message, exc.info)
ScraperError: ('Error in scraping forum user ID 689228', {'fallback': 'crawlera', 'status_code': 200, 'response_text': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml"><head>\n\t<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n\t<meta name="description" content="View the profile of Woultries" />\n\t\n\t<meta name="keywords" content="bitcoin, forum, bitcoin forum, bitcointalk" />\n\t<script language="JavaScript" type="text/javascript" src="https://bitcointalk.org/Themes/default/script.js"></script>\n\t<script language="JavaScript" type="text/javascript"><!-- // --><![CDATA[\n\t\tvar smf_theme_url = "https://bitcointalk.org/Themes/custom1";\n\t\tvar smf_images_url = "https://bitcointalk.org/Themes/custom1/images";\n\t\tvar smf_scripturl = "https://bitcointalk.org/index.php";\n\t\tvar smf_iso_case_folding = false;\n\t\tvar smf_charset = "ISO-8859-1";\n\t// ]]></script>\n\t<title>View the profile of Woultries</title><!--1403824c22b9a06f1f53570d09841c214a5e8d3bd7a33e092ace9b831c28a06f1f53570d09841c214a5e8d3bd7a3f714e0301e029ce8a06f1f53570d09841c214a5e8d3bd7a31ca9-->\n\t<link rel="stylesheet" type="text/css" href="https://bitcointalk.org/Themes/custom1/style.css" />\n\t <!--[if !IE]> -->\n\t <link rel="stylesheet" type="text/css" media="only screen and (min-device-width: 320px) and (max-device-width: 650px)" href="https://bitcointalk.org/Themes/custom1/mobile.css" />\n\t <!-- <![endif]-->\n\t<link rel="stylesheet" type="text/css" href="https://bitcointalk.org/Themes/default/print.css" media="print" /><style type="text/css">\n.atCgfgJWGsGUIhcLkldAXg > td {background-color: #E5E5E8; text-align:center;}\n.atCgfgJWGsGUIhcLkldAXg > td > table {margin-top:-5px}\n.atCgfgJWGsGUIhcLkldAXg .ugSkGdsCPzxbdWLpsEdpgw {display:inline-block;max-width:100%; min-width:100%; max-height:47px; overflow:hidden}\n.atCgfgJWGsGUIhcLkldAXg table,.atCgfgJWGsGUIhcLkldAXg tbody,.atCgfgJWGsGUIhcLkldAXg tr,.atCgfgJWGsGUIhcLkldAXg td {display:inline-block;max-width:100%; min-width:100%; overflow:hidden}\n.atCgfgJWGsGUIhcLkldAXg .ugSkGdsCPzxbdWLpsEdpgw table,.atCgfgJWGsGUIhcLkldAXg .ugSkGdsCPzxbdWLpsEdpgw tbody,.atCgfgJWGsGUIhcLkldAXg .ugSkGdsCPzxbdWLpsEdpgw tr,.atCgfgJWGsGUIhcLkldAXg .ugSkGdsCPzxbdWLpsEdpgw td {display:initial; max-width:none;min-width:none;overflow:visible}\n.bKrTdYfwLTlVsfbeyjFeDg {display:none !important}\n.lUjgdxJaxdMTddrdeVrtKg {display:none}\n.jwKDhfeWxnLcfBCyecqeiQ {padding: 1px 1px 0 1px;}\n.uWibcSqPaeVxMlulbawPwQ{color:#699C62; font-weight:bold; font-size:18px}\n.uWibcSqPaeVxMlulbawPwQ:link{color:#699C62; font-weight:bold; font-size:18px}\n.uWibcSqPaeVxMlulbawPwQ:visited{color:#699C62; font-weight:bold; font-size:18px}\n.ghyREvTTjwhddflejGTMZA{color:#00F30C;font-size:15px;font-weight:bold}\n.ghyREvTTjwhddflejGTMZA:link{color:#00F30C;font-size:15px;font-weight:bold}\n.ghyREvTTjwhddflejGTMZA:visited{color:#00F30C;font-size:15px;font-weight:bold}\n\n.LYGeFwrdaBhRFccdJJnhNQ:link {font-size:22px;font-weight:bold;color:orange}\n.LYGeFwrdaBhRFccdJJnhNQ:active {font-size:22px;font-weight:bold;color:orange}\n.LYGeFwrdaBhRFccdJJnhNQ:visited {font-size:22px;font-weight:bold;color:orange}\n.LYGeFwrdaBhRFccdJJnhNQ:hover {text-decoration:none !important;color:red}\n.UraeTfaxJQhgdyyDTAiPfA:link {font-size:24px;font-weight:bold;color:rgb(250,180,75)}\n.UraeTfaxJQhgdyyDTAiPfA:active {font-size:24px;font-weight:bold;color:rgb(250,180,75)}\n.UraeTfaxJQhgdyyDTAiPfA:visited {font-size:24px;font-weight:bold;color:rgb(250,180,75)}\n.UraeTfaxJQhgdyyDTAiPfA:hover {text-decoration:none !important;color:white;background-color:rgb(181,204,222)}\n.UraeTfaxJQhgdyyDTAiPfA {display:inline-block;margin: 3px;0;3px;0}\n.jujdHjyycozXkOneTefTxQ:hover {text-decoration:none !important;}\n.jujdHjyycozXkOneTefTxQ {font-size:22px;font-weight:bold;}\n.jiECKjcmBcxBwWBnZbvloQ {   width: 900px;   height: 44px;   max-width: 100%;   background: #5CB9F7;   display: flex;   justify-content: space-between;   align-items: center;   text-decoration: none !important;   font-size: 16px;   color: #fff !important;   font-family: arial, sans-serif;   overflow: hidden; }    .jiECKjcmBcxBwWBnZbvloQ button {     border: none;     background: #8EE000;     color: #fff;     outline: none;     font-size: 1em;     padding: 0.5em 1.2em;     margin-left: 0.3em;     border-radius: 2em;     text-transform: uppercase;     font-weight: 600;     pointer-events: none;   }    .jiECKjcmBcxBwWBnZbvloQ:hover .mpyzVFeFBRaGHMThjYleeQ span {   display: none; }  .jiECKjcmBcxBwWBnZbvloQ:hover .mpyzVFeFBRaGHMThjYleeQ span:nth-child(2) {   display: block; }  .mpyzVFeFBRaGHMThjYleeQ {   display: flex;   align-items: center; }    .mpyzVFeFBRaGHMThjYleeQ span {   margin-left: 0.1em;   font-size: 1em;   font-weight: 700;   letter-spacing: 0.5px;   font-size: 20px;   width: 11em;   text-align: center; }  .CqTmfibOdHJGjbfcuolJXQ {   display: inline-block; }  .mpyzVFeFBRaGHMThjYleeQ span:nth-child(2) {   display: none; }  .BHLcMhfTUrvDyWGyhULhvA {   display: flex;   background: #586A91;   height: 44px;   align-items: center;   justify-content: center;   padding: 0 1em 0 0.5em;   position: relative;   z-index: 2; }    .BHLcMhfTUrvDyWGyhULhvA:after {   position: absolute;   right: 100%;   top: 50%;   content: "";   width: 36px;   height: 36px;   background: #586A91;   border-radius: 0.5em;   transform: translate(50%, -50%) rotate(45deg);   z-index: -1; }    .BHLcMhfTUrvDyWGyhULhvA > span {   margin-right: 1em;   font-weight: 600;   font-size: 16px;   letter-spacing: 0.5px;   margin-top: 0.1em; }  @media (max-width: 725px) {   .jiECKjcmBcxBwWBnZbvloQ button {     display: none;   }   .mpyzVFeFBRaGHMThjYleeQ {     margin-left: 1em;   } }   @media (max-width: 550px) {   .BHLcMhfTUrvDyWGyhULhvA span span {     display: none;   } }  @media (max-width: 465px) {   .BHLcMhfTUrvDyWGyhULhvA {     display: none;   }   .jiECKjcmBcxBwWBnZbvloQ {     justify-content: center;   } }\n.eMVKbdsbayfFiofOsFUoJQ {   width: 900px;   height: 44px;   max-width: 100%;   background: #5CB9F7;   display: flex;   justify-content: space-between;   align-items: center;   text-decoration: none !important;   font-size: 16px;   color: #fff !important;   font-family: arial, sans-serif;   overflow: hidden; }    .eMVKbdsbayfFiofOsFUoJQ button {     border: none;     background: #8EE000;     color: #fff;     outline: none;     font-size: 1em;     padding: 0.5em 1.2em;     margin-left: 0.4em;     border-radius: 2em;     text-transform: uppercase;     font-weight: 600; cursor:pointer; transition: all 0.3s;   } button:hov

**Comment by joemarct** [comment]
@shawnlauzon  This is resolved by PR #232
