### ISSUE TITLE
ScraperError: ('Error in scraping forum posts of forum user ID 689228', {'status_code': 200, 'response_text': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://w

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-server#237]
View details in Rollbar: [https://rollbar.com/vlabs/Venue/items/44/](https://rollbar.com/vlabs/Venue/items/44/)

```
Traceback (most recent call last):
  File "/code/venue/tasks.py", line 168, in scrape_forum_profile
    start=posts_scrape_start.replace(tzinfo=None)
  File "/code/venue/scrapers/bitcointalk.py", line 370, in scrape_posts
    raise ScraperError(message, exc.info)
ScraperError: ('Error in scraping forum posts of forum user ID 689228', {'status_code': 200, 'response_text': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml"><head>\n\t<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />\n\t<meta name="description" content="Latest posts of:  Woultries" />\n\t\n\t<meta name="keywords" content="bitcoin, forum, bitcoin forum, bitcointalk" />\n\t<script language="JavaScript" type="text/javascript" src="https://bitcointalk.org/Themes/default/script.js"></script>\n\t<script language="JavaScript" type="text/javascript"><!-- // --><![CDATA[\n\t\tvar smf_theme_url = "https://bitcointalk.org/Themes/custom1";\n\t\tvar smf_images_url = "https://bitcointalk.org/Themes/custom1/images";\n\t\tvar smf_scripturl = "https://bitcointalk.org/index.php";\n\t\tvar smf_iso_case_folding = false;\n\t\tvar smf_charset = "ISO-8859-1";\n\t// ]]></script>\n\t<title>Latest posts of:  Woultries</title><!--4ff63d14cd4885552a2158dfade3b3a8c7d7c73a91a9-->\n\t<link rel="stylesheet" type="text/css" href="https://bitcointalk.org/Themes/custom1/style.css" />\n\t <!--[if !IE]> -->\n\t <link rel="stylesheet" type="text/css" media="only screen and (min-device-width: 320px) and (max-device-width: 650px)" href="https://bitcointalk.org/Themes/custom1/mobile.css" />\n\t <!-- <![endif]-->\n\t<link rel="stylesheet" type="text/css" href="https://bitcointalk.org/Themes/default/print.css" media="print" /><style type="text/css">\n.DyhMBcOjoHeyyvfYdabvqA > td {background-color: #E5E5E8; text-align:center;}\n.DyhMBcOjoHeyyvfYdabvqA > td > table {margin-top:-5px}\n.DyhMBcOjoHeyyvfYdabvqA .igGEMiapJUcwvhvFPbyBYQ {display:inline-block;max-width:100%; min-width:100%; max-height:47px; overflow:hidden}\n.DyhMBcOjoHeyyvfYdabvqA table,.DyhMBcOjoHeyyvfYdabvqA tbody,.DyhMBcOjoHeyyvfYdabvqA tr,.DyhMBcOjoHeyyvfYdabvqA td {display:inline-block;max-width:100%; min-width:100%; overflow:hidden}\n.DyhMBcOjoHeyyvfYdabvqA .igGEMiapJUcwvhvFPbyBYQ table,.DyhMBcOjoHeyyvfYdabvqA .igGEMiapJUcwvhvFPbyBYQ tbody,.DyhMBcOjoHeyyvfYdabvqA .igGEMiapJUcwvhvFPbyBYQ tr,.DyhMBcOjoHeyyvfYdabvqA .igGEMiapJUcwvhvFPbyBYQ td {display:initial; max-width:none;min-width:none;overflow:visible}\n.LSgQjaYbUnTFWeezAVztzw {display:none !important}\n.ViaEbkioYgpnBUxaeheEbQ {display:none}\n.wjRrjhsdwWgiPshyDCQeeQ {padding: 1px 1px 0 1px;}\n.uUYOmqSflqEiKefUBQMKKQ{color:#699C62; font-weight:bold; font-size:18px}\n.uUYOmqSflqEiKefUBQMKKQ:link{color:#699C62; font-weight:bold; font-size:18px}\n.uUYOmqSflqEiKefUBQMKKQ:visited{color:#699C62; font-weight:bold; font-size:18px}\n.xZfUivgkizjejeRFHJATvg{color:#00F30C;font-size:15px;font-weight:bold}\n.xZfUivgkizjejeRFHJATvg:link{color:#00F30C;font-size:15px;font-weight:bold}\n.xZfUivgkizjejeRFHJATvg:visited{color:#00F30C;font-size:15px;font-weight:bold}\n\n.BUkWkxCcyRzBlTrNcjUEgA:link {font-size:22px;font-weight:bold;color:orange}\n.BUkWkxCcyRzBlTrNcjUEgA:active {font-size:22px;font-weight:bold;color:orange}\n.BUkWkxCcyRzBlTrNcjUEgA:visited {font-size:22px;font-weight:bold;color:orange}\n.BUkWkxCcyRzBlTrNcjUEgA:hover {text-decoration:none !important;color:red}\n.xXuaAIyaUiliNAVDNsZccw:link {font-size:24px;font-weight:bold;color:rgb(250,180,75)}\n.xXuaAIyaUiliNAVDNsZccw:active {font-size:24px;font-weight:bold;color:rgb(250,180,75)}\n.xXuaAIyaUiliNAVDNsZccw:visited {font-size:24px;font-weight:bold;color:rgb(250,180,75)}\n.xXuaAIyaUiliNAVDNsZccw:hover {text-decoration:none !important;color:white;background-color:rgb(181,204,222)}\n.xXuaAIyaUiliNAVDNsZccw {display:inline-block;margin: 3px;0;3px;0}\n.CxEdrsGpePbAxabXUdgQFg:hover {text-decoration:none !important;}\n.CxEdrsGpePbAxabXUdgQFg {font-size:22px;font-weight:bold;}\n.csJCftWyjeWVhSzoIxdeOQ {   width: 900px;   height: 44px;   max-width: 100%;   background: #5CB9F7;   display: flex;   justify-content: space-between;   align-items: center;   text-decoration: none !important;   font-size: 16px;   color: #fff !important;   font-family: arial, sans-serif;   overflow: hidden; }    .csJCftWyjeWVhSzoIxdeOQ button {     border: none;     background: #8EE000;     color: #fff;     outline: none;     font-size: 1em;     padding: 0.5em 1.2em;     margin-left: 0.3em;     border-radius: 2em;     text-transform: uppercase;     font-weight: 600;     pointer-events: none;   }    .csJCftWyjeWVhSzoIxdeOQ:hover .iWeoDBaYPgnCOvWdHwaaYg span {   display: none; }  .csJCftWyjeWVhSzoIxdeOQ:hover .iWeoDBaYPgnCOvWdHwaaYg span:nth-child(2) {   display: block; }  .iWeoDBaYPgnCOvWdHwaaYg {   display: flex;   align-items: center; }    .iWeoDBaYPgnCOvWdHwaaYg span {   margin-left: 0.1em;   font-size: 1em;   font-weight: 700;   letter-spacing: 0.5px;   font-size: 20px;   width: 11em;   text-align: center; }  .ltruYgfyaNBgGyBbyyydaA {   display: inline-block; }  .iWeoDBaYPgnCOvWdHwaaYg span:nth-child(2) {   display: none; }  .gqXScChDtyRyleitOXuaPg {   display: flex;   background: #586A91;   height: 44px;   align-items: center;   justify-content: center;   padding: 0 1em 0 0.5em;   position: relative;   z-index: 2; }    .gqXScChDtyRyleitOXuaPg:after {   position: absolute;   right: 100%;   top: 50%;   content: "";   width: 36px;   height: 36px;   background: #586A91;   border-radius: 0.5em;   transform: translate(50%, -50%) rotate(45deg);   z-index: -1; }    .gqXScChDtyRyleitOXuaPg > span {   margin-right: 1em;   font-weight: 600;   font-size: 16px;   letter-spacing: 0.5px;   margin-top: 0.1em; }  @media (max-width: 725px) {   .csJCftWyjeWVhSzoIxdeOQ button {     display: none;   }   .iWeoDBaYPgnCOvWdHwaaYg {     margin-left: 1em;   } }   @media (max-width: 550px) {   .gqXScChDtyRyleitOXuaPg span span {     display: none;   } }  @media (max-width: 465px) {   .gqXScChDtyRyleitOXuaPg {     display: none;   }   .csJCftWyjeWVhSzoIxdeOQ {     justify-content: center;   } }\n.yOvgnGfjcOIpJRDrNIiijA {   width: 900px;   height: 44px;   max-width: 100%;   background: #5CB9F7;   display: flex;   justify-content: space-between;   align-items: center;   text-decoration: none !important;   font-size: 16px;   color: #fff !important;   font-family: arial, sans-serif;   overflow: hidden; }    .yOvgnGfjcOIpJRDrNIiijA button {     border: none;     background: #8EE000;     color: #fff;     outline: none;     font-size: 1em;     padding: 0.5em 1.2em;     margin-left: 0.4em;     border-radius: 2em;     text-transform: uppercase;     font-weight: 600; cursor:pointer; transition: all 0.3s;   } button:hover{transform: scale(1.05);}    .zZlkUakbdsfeghwwVCeOpQ:hover span{   display: none; }

**Comment by shawnlauzon** [comment]
Fixed in 38939aa
